export const GET_POSTS_REQUESTED = 'GET_POSTS_REQUESTED';
export const CREATE_POST_REQUESTED = 'CREATE_POST_REQUESTED';
export const UPDATE_POST_REQUESTED = 'UPDATE_POST_REQUESTED';
export const DELETE_POST_REQUESTED = 'DELETE_POST_REQUESTED';
export const GET_POST_BY_ID_REQUESTED = 'GET_POST_BY_ID_REQUESTED';
export const POSTS_SUCCESS = 'POSTS_SUCCESS';
export const POSTS_FAILED = 'POSTS_FAILED';
