export const GET_CONTRIES_REQUESTED = 'GET_CONTRIES_REQUESTED';
export const CONTRIES_SUCCESS = 'CONTRIES_SUCCESS';
export const CONTRIES_FAILED = 'CONTRIES_FAILED';

export const GET_UNIVERSITIES_REQUESTED = 'GET_UNIVERSITIES_REQUESTED';
export const UNIVERSITIES_SUCCESS = 'UNIVERSITIES_SUCCESS';
export const UNIVERSITIES_FAILED = 'UNIVERSITIES_FAILED';